"Name: \PR:ZSU_PRG_ENH_SECTION\IC:ZSU_PRG_ENH_SECTION\SE:END\EI
ENHANCEMENT 0 ZSU_ENH_IMPL_TEST.
WRITE:/ 'explicit enhancement Point static'.
WRITE :/ 'explicit enhancement Point dynamic'. "

END-ENHANCEMENT-SECTION.
ENDENHANCEMENT.
